import type { CrmAgentToolDefinition, CrmAgentToolDomain } from "@/lib/crm-agent-types";
import { attachCrmAgentDomainHandlers } from "@/lib/crm-agent-domain-tools";
import { attachCrmAgentDraftHandlers } from "@/lib/crm-agent-draft-tools";

const looseObjectSchema = {
  type: "object",
  additionalProperties: true,
};

const emptyObjectSchema = {
  type: "object",
  additionalProperties: false,
};

const crmAgentToolDefinitions: CrmAgentToolDefinition[] = [
  {
    name: "appointments.search",
    domain: "appointments",
    mode: "read",
    description: "Ищет записи по дате, клиенту, сотруднику, услуге или статусу.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.calendar.read",
    riskLevel: "low",
  },
  {
    name: "appointments.findAvailableSlots",
    domain: "schedule",
    mode: "read",
    description: "Ищет свободные окна по услуге, сотруднику, локации и датам.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.schedule.read",
    riskLevel: "low",
  },
  {
    name: "clients.search",
    domain: "clients",
    mode: "read",
    description: "Ищет клиентов по имени, телефону, почте, тегам или истории визитов.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.clients.read",
    riskLevel: "low",
  },
  {
    name: "services.search",
    domain: "services",
    mode: "read",
    description: "Ищет услуги и категории услуг.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.services.read",
    riskLevel: "low",
  },
  {
    name: "specialists.search",
    domain: "specialists",
    mode: "read",
    description: "Ищет сотрудников, их услуги, локации и активность.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.specialists.read",
    riskLevel: "low",
  },
  {
    name: "locations.search",
    domain: "locations",
    mode: "read",
    description: "Ищет локации и настройки филиалов.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.locations.read",
    riskLevel: "low",
  },
  {
    name: "promos.search",
    domain: "promos",
    mode: "read",
    description: "Ищет активные и прошлые акции.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.promos.read",
    riskLevel: "low",
  },
  {
    name: "analytics.workload",
    domain: "analytics",
    mode: "read",
    description: "Анализирует загрузку по дням, часам, сотрудникам и локациям.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.assistant.analytics.read",
    riskLevel: "low",
  },
  {
    name: "analytics.retention",
    domain: "analytics",
    mode: "read",
    description: "Находит клиентов, которые давно не приходили, и возможности вернуть их.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.assistant.analytics.read",
    riskLevel: "low",
  },
  {
    name: "reviews.search",
    domain: "reviews",
    mode: "read",
    description: "Ищет отзывы, негативную обратную связь и повторяющиеся проблемы.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.reviews.read",
    riskLevel: "low",
  },
  {
    name: "site.health",
    domain: "site",
    mode: "read",
    description: "Проверяет заполненность сайта, карточки услуг, карточки сотрудников и настройки поиска.",
    inputSchema: emptyObjectSchema,
    requiredPermission: "crm.settings.read",
    riskLevel: "low",
  },
  {
    name: "clients.draftCreate",
    domain: "clients",
    mode: "draft",
    description: "Prepare a client creation action with name, phone, email and birth date.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.clients.create",
    riskLevel: "medium",
  },
  {
    name: "clients.draftUpdate",
    domain: "clients",
    mode: "draft",
    description: "Prepare a client profile update action.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.clients.update",
    riskLevel: "medium",
  },
  {
    name: "appointments.draftCreate",
    domain: "appointments",
    mode: "draft",
    description: "Готовит создание записи с клиентом, услугой, сотрудником, локацией и временем.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.appointments.create",
    riskLevel: "high",
  },
  {
    name: "appointments.draftReschedule",
    domain: "appointments",
    mode: "draft",
    description: "Готовит перенос существующей записи на новое время, сотрудника или локацию.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.appointments.reschedule",
    riskLevel: "high",
  },
  {
    name: "appointments.draftCancel",
    domain: "appointments",
    mode: "draft",
    description: "Готовит отмену записи с комментарием.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.appointments.cancel",
    riskLevel: "high",
  },
  {
    name: "services.draftCreate",
    domain: "services",
    mode: "draft",
    description: "Готовит создание услуги с названием, длительностью, ценой, описанием и категорией.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.services.create",
    riskLevel: "medium",
  },
  {
    name: "services.draftUpdate",
    domain: "services",
    mode: "draft",
    description: "Готовит изменение услуги: название, описание, цена, длительность, категория или активность.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.services.update",
    riskLevel: "medium",
  },
  {
    name: "services.draftArchive",
    domain: "services",
    mode: "draft",
    description: "Готовит архивацию услуги.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.services.delete",
    riskLevel: "high",
  },
  {
    name: "specialists.draftUpdate",
    domain: "specialists",
    mode: "draft",
    description: "Готовит изменение публичности и описания сотрудника.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.specialists.update",
    riskLevel: "medium",
  },
  {
    name: "specialists.draftScheduleUpdate",
    domain: "schedule",
    mode: "draft",
    description: "Готовит изменение рабочего дня сотрудника: дата, локация, тип дня, время и заметка.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.schedule.update",
    riskLevel: "high",
  },
  {
    name: "locations.draftCreate",
    domain: "locations",
    mode: "draft",
    description: "Готовит создание локации с названием, адресом, описанием, телефоном и статусом.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.locations.create",
    riskLevel: "medium",
  },
  {
    name: "locations.draftUpdate",
    domain: "locations",
    mode: "draft",
    description: "Готовит изменение локации: название, адрес, описание, телефон или статус.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.locations.update",
    riskLevel: "medium",
  },
  {
    name: "promos.draftCreate",
    domain: "promos",
    mode: "draft",
    description: "Готовит создание акции с типом скидки, значением, датами и активностью.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.promos.create",
    riskLevel: "medium",
  },
  {
    name: "promos.draftUpdate",
    domain: "promos",
    mode: "draft",
    description: "Готовит изменение акции: название, тип, значение, даты или активность.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.promos.update",
    riskLevel: "medium",
  },
  {
    name: "promos.draftArchive",
    domain: "promos",
    mode: "draft",
    description: "Готовит архивацию акции.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.promos.update",
    riskLevel: "high",
  },
  {
    name: "reviews.draftReply",
    domain: "reviews",
    mode: "draft",
    description: "Prepare a review reply action for confirmation.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.reviews.manage",
    riskLevel: "medium",
  },
  {
    name: "notifications.draftSend",
    domain: "notifications",
    mode: "draft",
    description: "Prepare a direct client notification with marketing consent checks.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.assistant.campaigns.manage",
    riskLevel: "high",
  },
  {
    name: "notifications.draftCampaignSend",
    domain: "notifications",
    mode: "draft",
    description: "Prepare a campaign notification send through outbox.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.assistant.campaigns.manage",
    riskLevel: "high",
  },
  {
    name: "site.draftHomeCopyUpdate",
    domain: "site",
    mode: "draft",
    description: "Prepare a home page copy update action.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.settings.update",
    riskLevel: "medium",
  },
  {
    name: "site.draftSeoUpdate",
    domain: "site",
    mode: "draft",
    description: "Prepare a site SEO update action.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.settings.update",
    riskLevel: "medium",
  },
  {
    name: "action.prepare",
    domain: "insights",
    mode: "draft",
    description: "Готовит действие на подтверждение для записей, каталога, акций, отзывов, уведомлений или сайта.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.assistant.actions.confirm",
    riskLevel: "medium",
  },
  {
    name: "memory.update",
    domain: "memory",
    mode: "draft",
    description: "Готовит обновление памяти ассистента по аккаунту.",
    inputSchema: looseObjectSchema,
    requiredPermission: "crm.assistant.memory.manage",
    riskLevel: "medium",
  },
];

export const crmAgentToolRegistry: CrmAgentToolDefinition[] = attachCrmAgentDraftHandlers(
  attachCrmAgentDomainHandlers(crmAgentToolDefinitions),
);

export function getCrmAgentTool(name: string) {
  return crmAgentToolRegistry.find((tool) => tool.name === name) ?? null;
}

export function listCrmAgentToolsByDomain(domain: CrmAgentToolDomain) {
  return crmAgentToolRegistry.filter((tool) => tool.domain === domain);
}

export function listCrmAgentToolsForPermissions(permissions: string[]) {
  if (permissions.includes("crm.all")) return crmAgentToolRegistry;
  return crmAgentToolRegistry.filter((tool) => !tool.requiredPermission || permissions.includes(tool.requiredPermission));
}
