ALTER TABLE "AccountDomain"
  ADD COLUMN "status" TEXT NOT NULL DEFAULT 'PENDING',
  ADD COLUMN "sslStatus" TEXT NOT NULL DEFAULT 'PENDING',
  ADD COLUMN "lastCheckedAt" TIMESTAMP(3),
  ADD COLUMN "lastError" TEXT,
  ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE "AccountDomain"
SET "status" = CASE
  WHEN "verifiedAt" IS NOT NULL THEN 'ACTIVE'
  ELSE 'PENDING'
END;
