ALTER TYPE "IdentityProvider" ADD VALUE IF NOT EXISTS 'VK';
ALTER TYPE "IdentityProvider" ADD VALUE IF NOT EXISTS 'YANDEX';

ALTER TABLE "UserIdentity"
  ADD COLUMN IF NOT EXISTS "displayName" TEXT,
  ADD COLUMN IF NOT EXISTS "username" TEXT,
  ADD COLUMN IF NOT EXISTS "avatarUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "metadataJson" JSONB,
  ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

